# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainxtWPsr.ui'
##
## Created by: Qt User Interface Compiler version 6.9.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QHeaderView, QLabel, QLineEdit,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QTabWidget, QTableView,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        self.file_openMod = QAction(MainWindow)
        self.file_openMod.setObjectName(u"file_openMod")
        self.file_recentMod = QAction(MainWindow)
        self.file_recentMod.setObjectName(u"file_recentMod")
        self.file_newMod = QAction(MainWindow)
        self.file_newMod.setObjectName(u"file_newMod")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 801, 561))
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.global_refresh_button = QPushButton(self.tab_5)
        self.global_refresh_button.setObjectName(u"global_refresh_button")
        self.global_refresh_button.setGeometry(QRect(560, 470, 221, 51))
        self.global_reset_button = QPushButton(self.tab_5)
        self.global_reset_button.setObjectName(u"global_reset_button")
        self.global_reset_button.setGeometry(QRect(370, 470, 171, 41))
        self.global_name_label = QLabel(self.tab_5)
        self.global_name_label.setObjectName(u"global_name_label")
        self.global_name_label.setGeometry(QRect(10, 10, 101, 16))
        self.global_name_line_edit = QLineEdit(self.tab_5)
        self.global_name_line_edit.setObjectName(u"global_name_line_edit")
        self.global_name_line_edit.setGeometry(QRect(120, 10, 113, 22))
        self.global_desc_label = QLabel(self.tab_5)
        self.global_desc_label.setObjectName(u"global_desc_label")
        self.global_desc_label.setGeometry(QRect(10, 40, 101, 16))
        self.global_desc_line_edit = QLineEdit(self.tab_5)
        self.global_desc_line_edit.setObjectName(u"global_desc_line_edit")
        self.global_desc_line_edit.setGeometry(QRect(120, 40, 113, 22))
        self.label_6 = QLabel(self.tab_5)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(570, 10, 181, 21))
        self.global_version_label = QLabel(self.tab_5)
        self.global_version_label.setObjectName(u"global_version_label")
        self.global_version_label.setGeometry(QRect(10, 70, 71, 16))
        self.global_api_label = QLabel(self.tab_5)
        self.global_api_label.setObjectName(u"global_api_label")
        self.global_api_label.setGeometry(QRect(10, 100, 71, 16))
        self.global_discordrpc_label = QLabel(self.tab_5)
        self.global_discordrpc_label.setObjectName(u"global_discordrpc_label")
        self.global_discordrpc_label.setGeometry(QRect(10, 130, 81, 21))
        self.global_version_line_edit = QLineEdit(self.tab_5)
        self.global_version_line_edit.setObjectName(u"global_version_line_edit")
        self.global_version_line_edit.setGeometry(QRect(120, 70, 113, 22))
        self.global_api_line_edit = QLineEdit(self.tab_5)
        self.global_api_line_edit.setObjectName(u"global_api_line_edit")
        self.global_api_line_edit.setGeometry(QRect(120, 100, 113, 22))
        self.global_discordrpc_line_edit = QLineEdit(self.tab_5)
        self.global_discordrpc_line_edit.setObjectName(u"global_discordrpc_line_edit")
        self.global_discordrpc_line_edit.setGeometry(QRect(120, 130, 113, 22))
        self.global_openengine_button = QPushButton(self.tab_5)
        self.global_openengine_button.setObjectName(u"global_openengine_button")
        self.global_openengine_button.setGeometry(QRect(10, 470, 151, 51))
        self.tabWidget.addTab(self.tab_5, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.pushButton_21 = QPushButton(self.tab)
        self.pushButton_21.setObjectName(u"pushButton_21")
        self.pushButton_21.setGeometry(QRect(10, 10, 181, 51))
        self.pushButton_22 = QPushButton(self.tab)
        self.pushButton_22.setObjectName(u"pushButton_22")
        self.pushButton_22.setGeometry(QRect(10, 70, 181, 41))
        self.pushButton_23 = QPushButton(self.tab)
        self.pushButton_23.setObjectName(u"pushButton_23")
        self.pushButton_23.setGeometry(QRect(10, 120, 181, 41))
        self.label_11 = QLabel(self.tab)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(190, 10, 81, 21))
        self.label_12 = QLabel(self.tab)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(200, 40, 81, 16))
        self.label_13 = QLabel(self.tab)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(200, 70, 91, 16))
        self.label_14 = QLabel(self.tab)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(200, 100, 81, 16))
        self.label_15 = QLabel(self.tab)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(200, 130, 81, 16))
        self.lineEdit_7 = QLineEdit(self.tab)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(280, 10, 113, 22))
        self.lineEdit_8 = QLineEdit(self.tab)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setGeometry(QRect(280, 40, 113, 22))
        self.lineEdit_9 = QLineEdit(self.tab)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setGeometry(QRect(280, 70, 113, 22))
        self.lineEdit_10 = QLineEdit(self.tab)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.lineEdit_10.setGeometry(QRect(280, 100, 113, 22))
        self.lineEdit_11 = QLineEdit(self.tab)
        self.lineEdit_11.setObjectName(u"lineEdit_11")
        self.lineEdit_11.setGeometry(QRect(280, 130, 113, 22))
        self.pushButton_25 = QPushButton(self.tab)
        self.pushButton_25.setObjectName(u"pushButton_25")
        self.pushButton_25.setGeometry(QRect(580, 470, 211, 61))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.pushButton_14 = QPushButton(self.tab_2)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(10, 10, 141, 31))
        self.pushButton_15 = QPushButton(self.tab_2)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(10, 40, 141, 31))
        self.widget = QWidget(self.tab_2)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(180, 10, 601, 521))
        self.pushButton_16 = QPushButton(self.tab_2)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(10, 70, 141, 31))
        self.pushButton_19 = QPushButton(self.tab_2)
        self.pushButton_19.setObjectName(u"pushButton_19")
        self.pushButton_19.setGeometry(QRect(10, 110, 141, 31))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.pushButton_9 = QPushButton(self.tab_3)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(10, 70, 191, 31))
        self.pushButton_10 = QPushButton(self.tab_3)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(10, 10, 191, 31))
        self.pushButton_11 = QPushButton(self.tab_3)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(10, 40, 191, 31))
        self.pushButton_12 = QPushButton(self.tab_3)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(600, 490, 191, 31))
        self.pushButton_13 = QPushButton(self.tab_3)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(10, 100, 191, 31))
        self.pushButton_8 = QPushButton(self.tab_3)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(10, 130, 191, 31))
        self.label_10 = QLabel(self.tab_3)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(220, 10, 91, 31))
        self.lineEdit_4 = QLineEdit(self.tab_3)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(330, 10, 131, 21))
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.label = QLabel(self.tab_4)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 0, 141, 51))
        self.label_2 = QLabel(self.tab_4)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(230, 0, 181, 51))
        self.label_3 = QLabel(self.tab_4)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(510, 10, 231, 51))
        self.pushButton = QPushButton(self.tab_4)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(10, 60, 171, 51))
        self.pushButton_2 = QPushButton(self.tab_4)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(10, 120, 171, 61))
        self.pushButton_3 = QPushButton(self.tab_4)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(10, 190, 171, 61))
        self.pushButton_4 = QPushButton(self.tab_4)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(490, 60, 261, 61))
        self.pushButton_5 = QPushButton(self.tab_4)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(490, 130, 261, 51))
        self.pushButton_6 = QPushButton(self.tab_4)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(210, 60, 221, 51))
        self.pushButton_7 = QPushButton(self.tab_4)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(210, 120, 221, 61))
        self.pushButton_24 = QPushButton(self.tab_4)
        self.pushButton_24.setObjectName(u"pushButton_24")
        self.pushButton_24.setGeometry(QRect(10, 260, 171, 51))
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.tableView = QTableView(self.tab_6)
        self.tableView.setObjectName(u"tableView")
        self.tableView.setGeometry(QRect(180, 10, 611, 511))
        self.pushButton_26 = QPushButton(self.tab_6)
        self.pushButton_26.setObjectName(u"pushButton_26")
        self.pushButton_26.setGeometry(QRect(0, 10, 131, 31))
        self.pushButton_27 = QPushButton(self.tab_6)
        self.pushButton_27.setObjectName(u"pushButton_27")
        self.pushButton_27.setGeometry(QRect(10, 490, 111, 31))
        self.tabWidget.addTab(self.tab_6, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 22))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
#if QT_CONFIG(shortcut)
        self.global_name_label.setBuddy(self.global_name_line_edit)
        self.global_desc_label.setBuddy(self.global_desc_line_edit)
        self.global_version_label.setBuddy(self.global_version_line_edit)
        self.global_api_label.setBuddy(self.global_api_line_edit)
        self.global_discordrpc_label.setBuddy(self.global_discordrpc_line_edit)
        self.label_11.setBuddy(self.lineEdit_7)
        self.label_12.setBuddy(self.lineEdit_8)
        self.label_13.setBuddy(self.lineEdit_9)
        self.label_14.setBuddy(self.lineEdit_10)
        self.label_15.setBuddy(self.lineEdit_11)
        self.label_10.setBuddy(self.lineEdit_4)
#endif // QT_CONFIG(shortcut)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menuFile.addAction(self.file_openMod)
        self.menuFile.addAction(self.file_recentMod)
        self.menuFile.addAction(self.file_newMod)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.file_openMod.setText(QCoreApplication.translate("MainWindow", u"Open a Mod Folder", None))
        self.file_recentMod.setText(QCoreApplication.translate("MainWindow", u"Recents Mods", None))
        self.file_newMod.setText(QCoreApplication.translate("MainWindow", u"New Mod Folder", None))
        self.global_refresh_button.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
        self.global_reset_button.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.global_name_label.setText(QCoreApplication.translate("MainWindow", u"Mod Name", None))
        self.global_name_line_edit.setText(QCoreApplication.translate("MainWindow", u"TemplateMod", None))
        self.global_desc_label.setText(QCoreApplication.translate("MainWindow", u"Description", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Color", None))
        self.global_version_label.setText(QCoreApplication.translate("MainWindow", u"Version", None))
        self.global_api_label.setText(QCoreApplication.translate("MainWindow", u"Api Version", None))
        self.global_discordrpc_label.setText(QCoreApplication.translate("MainWindow", u"Discord RPC", None))
        self.global_openengine_button.setText(QCoreApplication.translate("MainWindow", u"Open Engine", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"Global", None))
        self.pushButton_21.setText(QCoreApplication.translate("MainWindow", u"Port VSlice (.fnfc, .json)", None))
        self.pushButton_22.setText(QCoreApplication.translate("MainWindow", u"Port Codename (.json)", None))
        self.pushButton_23.setText(QCoreApplication.translate("MainWindow", u"Port Psych (.json)", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Internal Name", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Visible Name", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Opponent", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Player", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Stage", None))
        self.pushButton_25.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Songs", None))
        self.pushButton_14.setText(QCoreApplication.translate("MainWindow", u"Port from Psych (.json)", None))
        self.pushButton_15.setText(QCoreApplication.translate("MainWindow", u"Port from VSlice (.json)", None))
        self.pushButton_16.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.pushButton_19.setText(QCoreApplication.translate("MainWindow", u"Open Engine Preview", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Characters", None))
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"See Preview", None))
        self.pushButton_10.setText(QCoreApplication.translate("MainWindow", u"Port From Psych (.json)", None))
        self.pushButton_11.setText(QCoreApplication.translate("MainWindow", u"Port From VSlice (.fnfs,.json)", None))
        self.pushButton_12.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.pushButton_13.setText(QCoreApplication.translate("MainWindow", u"Open a Existent Stage", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"Open Editor", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Name", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Stages", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"VSLICE", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"PSYCH", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"CODENAME", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Album", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Playable Character", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Sticker Pack", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"Week", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"Advanced Icon", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"Custom Setting", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"Custom Achievements", None))
        self.pushButton_24.setText(QCoreApplication.translate("MainWindow", u"Week", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"Generators", None))
        self.pushButton_26.setText(QCoreApplication.translate("MainWindow", u"Add Credit", None))
        self.pushButton_27.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QCoreApplication.translate("MainWindow", u"Credits", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
    # retranslateUi

